---
.github/workflows/ci.yaml:
  acceptance_matrix:
    set:
      - ---el7
      - el8
      - ---el9
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
.rubocop.yml:
  profiles:
    strict:
      configs:
        # TODO: Refactor at some point
        Style/OptionalBooleanParameter:
          Enabled: false
        RSpec/MultipleMemoizedHelpers:
          Enabled: false
        RSpec/RepeatedExampleGroupDescription:
          Enabled: false
spec/acceptance/nodesets/el7.yml:
  delete: true
spec/acceptance/nodesets/el8.yml:
  unmanaged: true
spec/acceptance/nodesets/el9.yml:
  delete: true
spec/acceptance/nodesets/debian-10.yml:
  delete: true
spec/acceptance/nodesets/debian-11.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-2004.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-2204.yml:
  delete: true
