name    'treydock-slurm_providers'
version '0.0.1'
source 'git://github.com/treydock/puppet-slurm_providers.git'
author 'treydock'
license 'Apache 2.0'
summary 'SLURM Puppet providers'
description 'SLURM Puppet providers'
project_page 'https://github.com/treydock/puppet-slurm_providers'
